### ISSUE TITLE
Is there any comparision between butterknife and findViewById ,is butterknife affect the load time?

### ISSUE THREAD

**Issue by Aeiric** [avast/android-butterknife-zelezny#107]

**Comment by TomasKypta** [comment]
This is a topic for https://github.com/JakeWharton/butterknife not for this project.
 
Anyway, it doesn't affect load time. 
Butterknife generates code to omit the findViewById() boilerplate,
it generates calls to findViewById(): `(T) view.findViewById(id)` 
Check https://github.com/JakeWharton/butterknife/blob/master/butterknife/src/main/java/butterknife/ButterKnife.java for more details.

Butterknife might affect compile time since it generates code during compile time.
