### ISSUE TITLE
Want to replace “@Bind” to “@XXX”

### ISSUE THREAD

**Issue by jwdtommy** [avast/android-butterknife-zelezny#113]
I was make a ViewInject tools like ButterKnife,but i named "@ViewAttached"so ,how can I modifiy the android-butterknife-zelezny for my feature?

**Comment by TomasKypta** [comment]
Hi,

the plugin is aimed to ease usage of ButterKnife library which uses annotations "@Bind", "@InjectView" or "@BindView" depending on the version.

If you want to use it for a different library, you have to fork it and adjust the behaviour.
And I'm afraid it will be a bigger refactoring since we really aim at ButterKnife.
